-- MySQL Script generated by MySQL Workbench
-- Thu Dec  3 01:44:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema importexport
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema importexport
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `importexport` DEFAULT CHARACTER SET utf8 ;
USE `importexport` ;

-- -----------------------------------------------------
-- Table `importexport`.`buyers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `importexport`.`buyers` (
  `Код покупателя` INT NOT NULL AUTO_INCREMENT,
  `Название фирмы` VARCHAR(45) NOT NULL,
  `Адрес` VARCHAR(45) NOT NULL,
  `Телефон` VARCHAR(45) NOT NULL,
  `Примечание` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Код покупателя`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `importexport`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `importexport`.`products` (
  `Код товара` INT NOT NULL AUTO_INCREMENT,
  `Название товара` VARCHAR(45) NULL DEFAULT NULL,
  `Единица измерения` VARCHAR(45) NULL DEFAULT NULL,
  `цена за единицу` INT NULL DEFAULT NULL,
  `Примечание` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Код товара`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `importexport`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `importexport`.`users` (
  `ID-пользователя` INT NOT NULL AUTO_INCREMENT,
  `Логин` VARCHAR(45) NOT NULL,
  `Пароль` VARCHAR(45) NOT NULL,
  `ФИО` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID-пользователя`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `importexport`.`export`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `importexport`.`export` (
  `Код операции экспорта` INT NOT NULL AUTO_INCREMENT,
  `Тип операции` VARCHAR(45) NOT NULL,
  `Дата получения` DATETIME NOT NULL,
  `Код товара` INT NOT NULL,
  `Номер накладной` INT NOT NULL,
  `Количество товара` INT NOT NULL,
  `Цена` INT NOT NULL,
  `Примечание` VARCHAR(45) NOT NULL,
  `Код покупателя` INT NOT NULL,
  `ID-пользователя` INT NOT NULL,
  PRIMARY KEY (`Код операции экспорта`),
  INDEX `Код товара_idx` (`Код товара` ASC) VISIBLE,
  INDEX `Код покупателя` (`Код покупателя` ASC) VISIBLE,
  INDEX `ID-пользователя_idx` (`ID-пользователя` ASC) VISIBLE,
  CONSTRAINT `Код покупателя`
    FOREIGN KEY (`Код покупателя`)
    REFERENCES `importexport`.`buyers` (`Код покупателя`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Код товара`
    FOREIGN KEY (`Код товара`)
    REFERENCES `importexport`.`products` (`Код товара`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ID-пользователя`
    FOREIGN KEY (`ID-пользователя`)
    REFERENCES `importexport`.`users` (`ID-пользователя`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `importexport`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `importexport`.`suppliers` (
  `Код поставщика` INT NOT NULL AUTO_INCREMENT,
  `Название фирмы` VARCHAR(45) NOT NULL,
  `Адрес` VARCHAR(45) NOT NULL,
  `Телефон` VARCHAR(45) NOT NULL,
  `Примечание` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Код поставщика`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `importexport`.`import`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `importexport`.`import` (
  `Код операции импорта` INT NOT NULL AUTO_INCREMENT,
  `Тип операции` VARCHAR(45) NOT NULL,
  `Дата` DATETIME NOT NULL,
  `ID-пользователя` INT NOT NULL,
  `Код товара` INT NOT NULL,
  `Код поставщика` INT NOT NULL,
  `Номер накладной` INT NOT NULL,
  `Количество товара` INT NOT NULL,
  `Цена` INT NOT NULL,
  `Примечание` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Код операции импорта`),
  INDEX `ID-пользователя_idx` (`ID-пользователя` ASC) VISIBLE,
  INDEX `Код товара_idx` (`Код товара` ASC) VISIBLE,
  INDEX `Код поставщика_idx` (`Код поставщика` ASC) VISIBLE,
  CONSTRAINT `ID-пользователя`
    FOREIGN KEY (`ID-пользователя`)
    REFERENCES `importexport`.`users` (`ID-пользователя`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Код поставщика`
    FOREIGN KEY (`Код поставщика`)
    REFERENCES `importexport`.`suppliers` (`Код поставщика`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Код товара`
    FOREIGN KEY (`Код товара`)
    REFERENCES `importexport`.`products` (`Код товара`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
